# Spawner config file

# Valid entities
valid_entities:
- Creeper
- Skeleton
- Spider
- Giant
- Zombie
- Slime
- Ghast
- PigZombie
- Enderman
- CaveSpider
- Silverfish
- Blaze
- LavaSlime
- EnderDragon
- WitherBoss
- Bat
- Witch
- Pig
- Sheep
- Cow
- Chicken
- Squid
- Wolf
- MushroomCow
- SnowMan
- Ozelot
- VillagerGolem
- EntityHorse
- Villager
- FireworksRocketEntity
- Guardian
- Endermite
- Rabbit

# Aliases
aliases:
    WitherBoss:
        - wither
    VillagerGolem:
        - irongolem
        - golem
    EntityHorse:
        - horse

# Preventing spawners being destroyed by explosions.
protect_from_explosions: true

# Default radius when removing entities with /spawner remove <entity>
remove_radius: 10

# Adds ability to limit the number of spawners a player can give/change.
#limit:
#    members: 0
#    vip: 3
#    elite: 6
#    godlike: 10

# Allow baby spawners (not yet implemented)
#allow_baby: false

# Allow mobs to wear armour (not yet implemented)
#allow_armour: true

# If less than 100 it will have a chance to not drop a spawner.
luck: 100

# The frequency that spawns from spawners are successful.
frequency:
    Creeper: 100
    Skeleton: 100
    Spider: 100
    Giant: 100
    Zombie: 100
    Slime: 100
    Ghast: 100
    PigZombie: 100
    Enderman: 100
    CaveSpider: 100
    Silverfish: 100
    Blaze: 100
    LavaSlime: 100
    EnderDragon: 100
    WitherBoss: 100
    Bat: 100
    Witch: 100
    Pig: 100
    Sheep: 100
    Cow: 100
    Chicken: 100
    Squid: 100
    Wolf: 100
    MushroomCow: 100
    SnowMan: 100
    Ozelot: 100
    VillagerGolem: 100
    EntityHorse: 100
    Villager: 100
    FireworksRocketEntity: 100
    Guardian: 100
    Endermite: 100
    Rabbit: 100

# Spawner drops
#
# type - Material type of the item to drop.
# amount - number of items to drop.
# damage - the amount of damage it has.
# data - the data value. For dropping a mob egg this would be the entity id.
# silk - true: silk touch for drops
#        false: no silk touch and silk touch still drops a spawner
#
# Example:
#
#    Creeper:
#        type: MONSTER_EGG
#        amount: 1
#        damage: 0
#        data: 50
#        silk: false
#
drops:
    Creeper: []
    Skeleton: []
    Spider: []
    Giant: []
    Zombie: []
    Slime: []
    Ghast: []
    PigZombie: []
    Enderman: []
    CaveSpider: []
    Silverfish: []
    Blaze: []
    LavaSlime: []
    EnderDragon: []
    WitherBoss: []
    Bat: []
    Witch: []
    Pig: []
    Sheep: []
    Cow: []
    Chicken: []
    Squid: []
    Wolf: []
    MushroomCow: []
    SnowMan: []
    Ozelot: []
    VillagerGolem: []
    EntityHorse: []
    Villager: []
    FireworksRocketEntity: []
    Guardian: []
    Endermite: []
    Rabbit: []
