name: ${project.name}
main: me.ryvix.spawner.Main
version: ${project.version}-b${buildNumber}
website: ${project.url}
author: ryvix
description: ${project.description}
commands:
  spawner:
    description: Allows switching of spawner entity types with /spawner <entity>
    usage: "/spawner help"
    aliases: [spwnr]
permissions:
  spawner.*:
    description: Gives all Spawner permissions.
    default: op
    children:
      spawner.remove: true
      spawner.reload: true
      spawner.set.*: true
      spawner.give.*: true
      spawner.give.others.*: true
      spawner.get: true
      spawner.break.*: true
      spawner.mine.*: true
      spawner.mine.nosilk.*: true
      spawner.list: true
      spawner.help: true
  spawner.remove:
    description: Gives access to use /spawner remove <entity> [radius] to remove entities around the player's location.
    default: op
  spawner.reload:
    description: Gives access to use /spawner reload to reload the plugin.
    default: op
  spawner.set.*:
    description: Gives access to use /spawner <entity> to set the spawner entity type.
    default: op
  spawner.give.*:
    description: Gives access to use /spawner give <entity> to give yourself a spawner of the given entity type.
    default: op
  spawner.give.others.*:
    description: Gives access to use /spawner give <entity> to give others a spawner of the given entity type.
    default: op
  spawner.get:
    description: Gives access to right-click a spawner or use /spawner to get the spawner entity type.
    default: op
  spawner.break.*:
    description: Allows players to break spawners as normal.
    default: op
  spawner.mine.*:
    description: Allows players to mine spawners with a silk touch enchanted tool.
    default: op
  spawner.mine.nosilk.*:
    description: Allows players to mine spawners without a silk touch enchanted tool.
    default: op
  spawner.place.*:
    description: Players with this permission will be prevented from placing spawners.
    default: op
  spawner.help:
    description: Gives access to use /spawner help
    default: op
  spawner.list:
    description: Gives access to use /spawner list
    default: op
