# Spawner config file

# Valid entities
valid_entities:
- bat
- blaze
- boat
- cave_spider
- chicken
- cow
- creeper
- donkey
- elder_guardian
- ender_dragon
- enderman
- endermite
- evocation_illager
- fireworks_rocket
- ghast
- giant
- guardian
- horse
- husk
- llama
- magma_cube
- mooshroom
- mule
- ocelot
- pig
- polar_bear
- rabbit
- sheep
- shulker
- silverfish
- skeleton
- skeleton_horse
- slime
- snowman
- spider
- squid
- stray
- vex
- villager
- villager_golem
- vindication_illager
- witch
- wither
- wither_skeleton
- wolf
- xp_orb
- zombie
- zombie_horse
- zombie_pigman
- zombie_villager

# Aliases
aliases:
    fireworks_rocket:
        - fireworks
    ocelot:
        - cat
    rabbit:
        - bunny
    villager_golem:
        - golem
        - irongolem
    xp_orb:
        - xp

# Preventing spawners being destroyed by explosions.
protect_from_explosions: true

# Spawners will drop from explosions.
# protect_from_explosions must be false for this to work.
drop_from_explosions: false

# Default radius when removing entities with /spawner remove <entity>
remove_radius: 10

# If less than 100 it will have a chance to not drop a spawner.
luck: 100

# The frequency that spawns from spawners are successful.
frequency:
    bat: 100
    blaze: 100
    boat: 100
    cave_spider: 100
    chicken: 100
    cow: 100
    creeper: 100
    donkey: 100
    elder_guardian: 100
    ender_dragon: 100
    enderman: 100
    endermite: 100
    evocation_illager: 100
    fireworks_rocket: 100
    ghast: 100
    giant: 100
    guardian: 100
    horse: 100
    husk: 100
    llama: 100
    magma_cube: 100
    mooshroom: 100
    mule: 100
    ocelot: 100
    pig: 100
    polar_bear: 100
    rabbit: 100
    sheep: 100
    shulker: 100
    silverfish: 100
    skeleton: 100
    skeleton_horse: 100
    slime: 100
    snowman: 100
    spider: 100
    squid: 100
    stray: 100
    vex: 100
    villager: 100
    villager_golem: 100
    vindication_illager: 100
    witch: 100
    wither: 100
    wither_skeleton: 100
    wolf: 100
    xp_orb: 100
    zombie: 100
    zombie_horse: 100
    zombie_pigman: 100
    zombie_villager: 100

# Spawner drops
#
# type - Material type of the item to drop.
# amount - number of items to drop.
# damage - the amount of damage it has.
# data - the data value. For dropping a mob egg this would be the entity id.
# silk - true: silk touch for drops
#        false: no silk touch and silk touch still drops a spawner
#
# Example:
#
#    Creeper:
#        type: MONSTER_EGG
#        amount: 1
#        damage: 0
#        data: 50
#        silk: false
#
drops:
    bat: []
    blaze: []
    boat: []
    cave_spider: []
    chicken: []
    cow: []
    creeper: []
    donkey: []
    elder_guardian: []
    ender_dragon: []
    enderman: []
    endermite: []
    evocation_illager: []
    fireworks_rocket: []
    ghast: []
    giant: []
    guardian: []
    horse: []
    husk: []
    llama: []
    magma_cube: []
    mooshroom: []
    mule: []
    ocelot: []
    pig: []
    polar_bear: []
    rabbit: []
    sheep: []
    shulker: []
    silverfish: []
    skeleton: []
    skeleton_horse: []
    slime: []
    snowman: []
    spider: []
    squid: []
    stray: []
    vex: []
    villager: []
    villager_golem: []
    vindication_illager: []
    witch: []
    wither: []
    wither_skeleton: []
    wolf: []
    xp_orb: []
    zombie: []
    zombie_horse: []
    zombie_pigman: []
    zombie_villager: []

# Place spawners directly into player inventories when broken?
# true or false
break_into_inventory: false

# If break_into_inventory is true then you can use this option to control whether to prevent breaking spawners when the
# player's inventory is full. Set to false to drop the spawner on the ground. Set to true to prevent breaking.
prevent_break_if_inventory_full: false
